# Generated by Django 4.1.7 on 2023-05-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='problems',
            new_name='task_detail',
        ),
    ]
