# Generated by Django 4.1.7 on 2023-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_problems_task_task_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='role',
            field=models.CharField(choices=[('PM', 'project manager'), ('FD', 'frontend developer'), ('BD', 'backend developer'), ('UD', 'ui/ux designer'), ('SEO', 'SEO')], default='FD', max_length=3),
            preserve_default=False,
        ),
    ]
