# Generated by Django 4.1.7 on 2023-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_task_assigned_to_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.CharField(choices=[('AD', 'admin'), ('PM', 'project manager'), ('FD', 'frontend developer'), ('BD', 'backend developer'), ('UD', 'ui/ux designer'), ('SEO', 'SEO')], max_length=3),
        ),
    ]
