# Generated by Django 4.1.7 on 2023-05-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_created_by_manager',
            field=models.BooleanField(default=False),
        ),
    ]
