# Generated by Django 4.1.7 on 2023-05-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_is_created_by_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_created_by_manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
