# Generated by Django 4.1.7 on 2023-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('AD', 'admin'), ('PM', 'project manager'), ('FD', 'frontend developer'), ('BD', 'backend developer'), ('UD', 'ui/ux designer'), ('SEO', 'SEO')], default='AD', max_length=3),
        ),
    ]
